name: giter8

on:
  push:
    branches: [master]

  schedule:
    - cron: "30 18 * * *" # run at 00:00 AM IST

jobs:
  g8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout csw repo
        uses: actions/checkout@v2
        with:
          repository: tmtsoftware/csw

      - uses: olafurpg/setup-scala@v5
        with:
          java-version: adopt@1.11

      - name: Cache ~/.cache
        uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-coursier-${{ hashFiles('project/Libs.scala') }}
          restore-keys: |
            ${{ runner.os }}-coursier-

      - name: Cache ~/.sbt
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('project/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Publish Local
        run: sbt clean publishLocal

      - name: Giter8 Compile
        run: |
          sbt new tmtsoftware/csw.g8 --branch dev --name=galil --csw_version='0.1.0-SNAPSHOT' 
          cd galil 
          sbt clean test

      - name: Build Status
        if: always()
        id: status
        run: |
          if [[ ${{job.status}} == Success ]]
          then
          echo ::set-output name=title::'SUCCESS'
          echo ::set-output name=color::'#00FF00'
          else
          echo ::set-output name=title::'FAILURE'
          echo ::set-output name=color::'#FF0000'
          fi

      - name: Notify slack
        if: always()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"#giter8-nightly-build\", \"attachments\": [ { \"title\":\"${{ steps.status.outputs.title }}\", \"text\": \"[ ${{ github.event.repository.name }} ] : [ ${{ github.workflow }} ] : [ ${{ github.ref }} ] \n https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\", \"color\": \"${{ steps.status.outputs.color }}\" } ]}'
