name: release

on:
  pull_request:
    types:
      - labeled
      - opened
      - edited
    branches: master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: olafurpg/setup-scala@v5
        with:
          java-version: adopt@1.11

      - name: Release Version
        id: csw
        run: |
          CSW_VERSION=$(grep "csw.version" ./src/main/g8/default.properties 2>/dev/null | cut -d'=' -f2)
          echo ::set-output name=version::$CSW_VERSION

      - name: Merge
        uses: "pascalgn/automerge-action@135f0bdb927d9807b5446f7ca9ecc2c51de03c4a"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "release"
          MERGE_FORKS: "false"

      - name: Giter8 Compile
        run: |
          sbt new tmtsoftware/csw.g8 --name=galil --csw_version=${{ steps.csw.outputs.version }}
          cd galil 
          sbt clean test

      - name: Tag Repo
        run: |
          VERSION=${{ steps.csw.outputs.version }}
          git tag v$VERSION
          git push origin v$VERSION
